package backend.task;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

@Entity // make this a db table
public class Task {
	@Id // this is the primary key (autogenerated)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	private String title;
	private boolean completed;

	// default constructor
	public Task(){
	}
	
	// std constructor
	public Task(String title, boolean completed){
		this.title = title;
		this.completed = completed;
	}

	// get Fn
	public long getId(){
		return id;
	}
	public String getTitle(){
		return title;
	}
	public boolean isCompleted(){
		return completed;
	}
	
	// set Fn
	public void setTitle(String title){
		this.title = title;
	}
	public void setCompleted(boolean completed){
		this.completed = completed;
	}
}
